### PR TITLE
Gelf writer

### PR DESCRIPTION
**Pull request by dploeger**
This PR adds support for the [Gelf Writer](https://github.com/jmxtrans/jmxtrans/wiki/GELFWriter) configuration for each query in JMXTrans.

### CODE REVIEW

**Comment by dploeger** [comment]
@thrnio I'd really like to get this implemented. Any questions or concerns? Thanks

**Comment by dploeger** [comment]
@thrnio Sorry to bother you again. Are you still maintaining this module? We could also adopt it.

**Comment by dploeger** [comment]
Ping @genebean @mrodm

**Comment by genebean** [comment]
👋🏻 Hey, thanks for the PR and the ping! Am I reading this right that this should be fully backwards compatible?

**Comment by genebean** [comment]
I'd love to chat with one or both of you about ownership of this module if you are game. Hit me up on the puppet community slack if you are interested - I am genebean there.

**Comment by dploeger** [comment]
@genebean Wrote you there.

**Comment by dploeger** [comment]
Thanks for merging and yeah, it should be fully backwards compatible.

**Pull request merged**
